# Generated by Django 4.2.7 on 2024-02-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete flag')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=40, verbose_name='password')),
                ('email', models.EmailField(max_length=254, verbose_name='user_email')),
                ('is_active', models.BooleanField(default=False, verbose_name='active_status')),
                ('user_type', models.IntegerField(verbose_name='user_type')),
                ('user_birthday', models.DateField(verbose_name='user_birthday')),
            ],
            options={
                'db_table': 's_user_account',
            },
        ),
    ]
