# Generated by Django 4.2.7 on 2024-02-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_birthday',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
    ]
