# Generated by Django 4.2.7 on 2024-02-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_account_user_birthday_alter_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_type',
        ),
    ]
